
## Data

The data set utilized in this paper, `Credit.csv`, contains 400 observations of 12 variables. Each observation corresponds to one person, and 11 of the variables are of general interest: `Income`, `Limit`, `Rating`, `Cards`, `Age`, `Education`, `Gender`, `Student`, `Married`, `Ethnicity`, and `Balance`. The  variable `X` is an index.

This dataset is free to access online at the following url http://www-bcf.usc.edu/~gareth/ISL/Credit.csv. Alternatively, you can visit the author's GitHub repository [My Github Account](http://www.github.com/jwilber) to access it as well.

For this paper, we will use the following variables: `Income`, `Limit`, `Rating`, `Cards`, `Age`, `Education`, `Gender`, `Student`, `Married`, `Ethnicity`, and `Balance`. `Income` refers to the person's income in thousands of dollars. `Limit` refers to the person's credit card limit in dollars. `Rating` refers to the person's credit rating. `Cards` refers to the number of cards the person has. `Education` refers to the number of years of education the person has completed. `Student` and `Married` are logical, answering the question of whether the person is currently a student and whether they are married. `Ethnicity` can take the values "Asian", "Caucasian", or "African American".  `Balance` refers to the person's credit card balance in dollars. `Age` and `Gender` are self-explanatory.

In our analysis, we will treat `Balance` as the dependent variable and the other 10 variables of interest as the independent variables.

